language: "th-TH"

reviews:
  profile: "assertive" # assertive = รีวิวแบบเข้มงวด, chill = รีวิวแบบสบายๆ
  request_changes_workflow: false
  high_level_summary: true
  poem: true # แต่งกลอนปิดท้ายแต่ละ PR review
